# Use root/example as user/password credentials
version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      TZ: Asia/Shanghai # 设置时区
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: Aa123456
      # MONGO_INITDB_DATABASE: hmmm
    restart: 'no' # 我的是本地虚拟机，测试环境，不需要每次自动重启always
    ports:
      - "27017:27017"
    # dns:
    #   - 114.114.114.114
    #   - 8.8.8.8
    privileged: true #容器拥有root权限
    volumes:
      - "/etc/localtime:/etc/localtime" # 时区f
      - "./mongodb/data/db:/data/db" # 挂载数据目录
      - "./mongodb/data/log:/var/log/mongodb" # 挂载日志目录
      - "./mongodb/data/config:/etc/mongo" # 挂载配置目录
      # -  "/etc/resolv.conf:/etc/resolv.conf" #  通过echo的方式修改宿主机文件

  redis:
    image: redis:latest # 指定服务镜像，最好是与之前下载的redis配置文件保持一致
    container_name: my_redis # 容器名称
    restart: 'no' # 重启方式
    environment:
      - TZ=Asia/Shanghai # 设置时区
    volumes: # 配置数据卷
      - ./redis/data:/data
      - ./redis/log/:/logs
      - ./redis/redis.conf:/etc/redis/redis.conf
    ports: # 映射端口
      - "6379:6379"
    # sysctls: # 设置容器中的内核参数
      # - net.core.somaxconn=1024
      # - vm.overcommit_memory=1
    command:
      /bin/sh -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf && redis-server /etc/redis/redis.conf --requirepass 'Aa123456' --appendonly yes" # 指定配置文件并开启持久化
    privileged: true # 使用该参数，container内的root拥有真正的root权限。否则，container内的root只是外部的一个普通用户权限

  minio:
    image: minio/minio:latest
    container_name: minio
    ports: # 映射端口
      - "9000:9000" # api 端口  默认
      - "9090:9090" # console 端口 随机指定
    restart: 'no'
    # command: server /data #指定容器中的目录 /data
    command: server --console-address ':9090' --address ':9000' /data 
    #--console-address指定控制台端口
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: Aa123456 #大于等于8位
    logging:
      options:
        max-size: "50M" # 最大文件上传限制
        max-file: "10"
      driver: json-file
    volumes:
      - ./minio/data:/data # 映射当前目录下的data目录至容器内/data目录
      - ./minio/config:/root/.minio/ #映射配置目录

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: 'no'
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
    ports:
    - "8080:8080"
    environment:
      TZ: Asia/Shanghai
      # NGINX_HOST: foobar.com
      # NGINX_PORT: 80
    volumes:
    - ./nginx/templates:/etc/nginx/templates
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/conf.d/:/etc/nginx/conf.d
    - ./nginx/logs:/var/log/nginx
    - ./nginx/dist:/etc/nginx/dist
    privileged: true # 使用该参数，container内的root拥有真正的root权限

